# Generated by Django 5.0.5 on 2024-06-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='email',
            field=models.EmailField(help_text='Campo obrigatório. Email para contato dos membros que estão submetendo trabalhos.', max_length=100, null=True, verbose_name='Email oficial da comissão científica *'),
        ),
    ]
