# Generated by Django 5.0.5 on 2024-06-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(db_index=True, help_text='* Campos obrigatórios', max_length=100, unique=True, verbose_name='Título do aviso *')),
                ('texto', models.TextField(help_text='Máximo de 500 caracteres', max_length=500, verbose_name='Texto da notícia *')),
                ('data', models.DateField(auto_now=True, verbose_name='Data do aviso')),
                ('destinatario', models.CharField(choices=[('TODOS', 'Todos'), ('COORDENADOR', 'Coordenador de Evento'), ('MEMBRO', 'Membro')], default='TODOS', max_length=20, verbose_name='Destinatários *')),
                ('enviado', models.BooleanField(default=False, help_text='Se marcado, aviso é enviado uma vez aos detinatários ativos', verbose_name='Selecione para enviar aviso por email aos destinatários')),
                ('is_active', models.BooleanField(default=True, help_text='Se ativo, o aviso aparece na home de atletas', verbose_name='Selecione para publicar na home dos usuários o aviso')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'aviso',
                'verbose_name_plural': 'avisos',
                'ordering': ['-data', 'titulo'],
            },
        ),
    ]
