# Generated by Django 3.0.4 on 2020-10-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='* Campos obrigatórios', max_length=20, unique=True, verbose_name='Código do objeto *')),
                ('tipo', models.CharField(choices=[('LIVRO', 'Livro'), ('JOGO ELETRÔNICO', 'Jogo Eletrônico'), ('VESTUÁRIO', 'Vestuário')], help_text='* Campos obrigatórios', max_length=15, verbose_name='Tipo do objeto *')),
                ('descricao', models.CharField(help_text='* Campos obrigatórios', max_length=100, verbose_name='Detalhes do objeto (resumo ou o título) *')),
                ('valor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Valor do objeto')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'objeto',
                'verbose_name_plural': 'objetos',
                'ordering': ['codigo', 'descricao'],
            },
        ),
    ]
