# Generated by Django 3.1.2 on 2020-10-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objeto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='arquivo_foto',
            field=models.FileField(blank=True, help_text='Tamanho máximo de 64MB', null=True, upload_to='midias', verbose_name='Foto do objeto'),
        ),
    ]
