# Generated by Django 3.0.4 on 2024-04-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='arquivo_medicamentos',
            field=models.FileField(blank=True, help_text='Arquivos com extensão .csv', null=True, upload_to='midias', verbose_name='Relação medicamentos'),
        ),
    ]
