# Generated by Django 3.0.4 on 2020-10-08 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objeto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataEmprestimo', models.DateTimeField(help_text='Use dd/mm/aaaa', max_length=10, verbose_name='Data do empréstimo ')),
                ('devolvido', models.BooleanField(default='Não', verbose_name='Já foi devolvido? ')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
                ('locador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Locador')),
                ('objeto', models.ManyToManyField(to='objeto.Objeto', verbose_name='Objeto(s) emprestado(s)')),
            ],
            options={
                'verbose_name': 'emprestimo',
                'verbose_name_plural': 'emprestimos',
                'ordering': ['locador'],
                'unique_together': {('locador', 'dataEmprestimo')},
            },
        ),
    ]
