# Generated by Django 3.1.2 on 2020-10-15 22:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emprestimo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='dataEmprestimo',
            new_name='data_emprestimo',
        ),
        migrations.AlterUniqueTogether(
            name='emprestimo',
            unique_together={('locador', 'data_emprestimo')},
        ),
    ]
