# Generated by Django 3.1.2 on 2020-10-15 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimo', '0003_auto_20201015_1927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['-em_emprestimo', 'locador'], 'verbose_name': 'emprestimo', 'verbose_name_plural': 'emprestimos'},
        ),
    ]
