# Generated by Django 5.0.5 on 2024-06-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(db_index=True, help_text='* Campo obrigatório', max_length=100, unique=True, verbose_name='Tipo de evento *')),
                ('is_active', models.BooleanField(default=True, help_text='Se ativo, o tipo pode ser usada no sistema', verbose_name='Ativo')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, verbose_name='Hash')),
            ],
            options={
                'verbose_name': 'tipo evento',
                'verbose_name_plural': 'tipos evento',
                'ordering': ['-is_active', 'descricao'],
            },
        ),
    ]
