# Generated by Django 5.0.5 on 2024-06-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoevento',
            options={'ordering': ['-is_active', 'descricao'], 'verbose_name': 'Descrição', 'verbose_name_plural': 'Descrições'},
        ),
    ]
