# Generated by Django 5.0.5 on 2024-06-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='area',
            field=models.CharField(choices=[('HUMANAS', 'Ciências Humanas'), ('SAUDE', 'Ciências da Saúde'), ('SOCIAIS', 'Ciências Sociais'), ('TECNOLOGICA', 'Ciências Tecnológicas')], help_text='Escolha área de interesse de trabalho', max_length=11, verbose_name='Área de pesquisa do usuário *'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='instituicao',
            field=models.CharField(help_text='Registre a instituição, ou universidade, ou empresa', max_length=50, verbose_name='Instituição a que pertence *'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='titulacao',
            field=models.CharField(blank=True, choices=[('TECNICO', 'Técnico'), ('GRADUANDO', 'Graduando'), ('GRADUADO', 'Graduado'), ('ESPECIALISTA', 'Especialista'), ('MESTRE', 'Mestre'), ('DOUTOR', 'Doutor')], help_text='Selecione a maior titulação', max_length=15, null=True, verbose_name='Titulação'),
        ),
    ]
