# Generated by Django 5.0.5 on 2024-06-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_area_alter_usuario_instituicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='celular',
            field=models.CharField(help_text='Use DDD, por exemplo 55987619832', max_length=14, verbose_name='Número celular com DDD *'),
        ),
    ]
