# Generated by Django 5.0.5 on 2024-06-18 14:26

import django.contrib.auth.models
import usuario.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_celular'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
                ('administradores', usuario.models.AdministradorAtivoManager()),
                ('coordenadores', usuario.models.CoordenadorAtivoManager()),
                ('membros', usuario.models.MembroAtivoManager()),
                ('usuarios_ativos', usuario.models.UsuarioAtivoManager()),
            ],
        ),
    ]
